# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresults',
            name='polling_unit_uniqueid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniquewardid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
